<?php
$this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'), 'screen')
                 ->appendStylesheet($this->baseUrl('css/screen-alt.css'), 'alternative')
                 ->appendStylesheet($this->baseUrl('css/print.css'), 'print');
$this->headStyle()->captureStart(); ?>
.style1 {color: #C1FF64}
<?php $this->headStyle()->captureEnd();
echo $this->doctype(); ?>
<html lang="en">
    <head>
<?php 
echo $this->headMeta()->setIndent(4) . PHP_EOL;
echo $this->headTitle()->setIndent(4) . PHP_EOL;
echo $this->headLink()->setIndent(4) . PHP_EOL;
echo $this->headStyle()->setIndent(4) . PHP_EOL;
echo $this->headScript()->setIndent(4) . PHP_EOL;
?>
    </head>
    <body>
        <!-- For non-visual user agents: -->
        <div id="top"><a href="#main-copy" class="doNotDisplay doNotPrint">Skip to main content.</a></div>
        <!-- ##### Header ##### -->
        <div id="header">
            <div class="superHeader">
                <div class="left"> <span class="doNotDisplay">Related sites:</span> <a href="./index.html">Link 1</a> | <a href="./index.html">Link 2</a> </div>
                    <div class="right"> <span class="doNotDisplay">More related sites:</span> 
                    <a href="./index.html">Link 3</a> | <a href="./index.html">Link 4</a> | 
                    <a href="./index.html">Link 5</a> | <a href="./index.html">Link 6</a> | 
                    <a href="./index.html">Link 7</a>
                    </div>
                </div>
            <div class="midHeader">
                <h1 class="headerTitle">Sinorca 2.0</h1>
            </div>
            <div class="subHeader">
                <span class="doNotDisplay">Navigation:</span>
                <a href="./index.html">Home</a> |
                <a href="./index.html" class="highlight">Sinorca 2.0</a> |
                <a href="./index.html">Other</a> |
                <a href="./index.html">Header</a> |
                <a href="./index.html">Links</a>
            </div>
        </div>
        <!-- ##### Side Bar ##### -->
        <div id="side-bar">
            <div>
                <p class="sideBarTitle">Navigate this page</p>
                <ul>
                <li><a href="#introduction">&rsaquo; Introduction</a></li>
                <li><a href="#cross-browser" title="Improved cross-browser compatibility">&rsaquo; Cross-browser</a></li>
                <li><a href="#stylesheets" title="Modified stylesheets">&rsaquo; Stylesheets</a></li>
                <li><a href="#accessibility" title="Improved accessibility">&rsaquo; Accessibility</a></li>
                </ul>
            </div>
            <div>
                <p class="sideBarTitle">Sample menu</p>
                <ul>
                <li><a href="./index.html">&rsaquo; Sidebar</a></li>
                <li><span class="thisPage">&raquo; Links</span></li>
                <li><a href="./index.html">&rsaquo; Go</a></li>
                <li><a href="./index.html">&rsaquo; Here</a></li>
                <li><a href="http://www.oswd.org/email.phtml?user=haran">&rsaquo; Submit comments</a></li>
                </ul>
            </div>
            <div class="lighterBackground">
                <p class="sideBarTitle">Alternative stylesheet</p>
                <span class="sideBarText">
                    Sinorca contains an alternative stylesheet that renders this side bar differently.
                </span>
                <span class="sideBarText">
                    To view the alternative stylesheet in (certain)
                <span class="titleTip" title="eg: Mozilla, Camino, Netscape 6+">Gecko-based browsers,
                    select <em>Sinorca (alternative)</em> from the <em>View</em> &rsaquo; <em>Use Style</em>
                    submenu.
                </span>
            </div>
            <div>
                <p class="sideBarTitle">Validation</p>
                <span class="sideBarText">
                    Validate the <a href="http://validator.w3.org/check/referer">XHTML</a> and
                <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> of this page.
                </span>
            </div>
        </div>
        <!-- ##### Main Copy ##### -->
        <div id="main-copy">
<?php echo $this->layout()->content; ?>
        </div>
        <!-- ##### Footer ##### -->
        <div id="footer">    
            <div class="left">
            </div>
            <br class="doNotDisplay doNotPrint" />
            <div class="right">
                This design is (almost) public domain.<br />
                <a href="/developed" class="doNotPrint">Developed by</a><br />
                Courtesy of <a href="http://www.openwebdesign.org" target="_blank">Open Web Design</a> 
            </div>
        </div>
    </body>
</html>